# Generated by Django 5.1.2 on 2024-11-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azkar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, default=1, null=True)),
                ('reward', models.TextField(blank=True, null=True)),
                ('when', models.CharField(blank=True, max_length=255, null=True)),
                ('where', models.CharField(blank=True, max_length=255, null=True)),
                ('why', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='ar', max_length=10, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
